---
version: "2.0"
services:
  app:
    image: quay.io/vpavlin0/comfyui@sha256:07bf4c2b7be976d573c42849f96dcf2ef0e89a5aaf5d09a66a66c1d087fd3851 #prep tag
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
    env:
      - "ENABLE_MANAGER=true"
      - "VAEURLS="
      - "MODELURLS="
      - "UPSCALEURLS="
      - "COMMANDLINE_ARGS=--listen 0.0.0.0 --port 9090"
      - "DELETE_EVERY_12HRS=true"
    command:
      - sh
      - -c
    args:
      - >
          chown -R fcb:fcb /comfyui/models

          bash /comfyui/custom_entrypoint.sh
    
    params:
      storage:
        models:
          mount: /comfyui/models
          readOnly: false
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 6.0
        memory:
          size: 35Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
        storage:
          - size: 50Gi
            name: models
            attributes:
              persistent: true
              class: beta3
  placement:
    akash:
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1
